version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add --no-cache python3-dev build-base
            python3 -m ensurepip
            export VERIFY_SSL=False
            python3 -m pip install --upgrade pip
            python3 -m pip install --trusted-host pypi.python.org setuptools docker-compose==1.24.0

      - run:
          name: Update Python version
          command: |
            apk add --no-cache python3
            ln -sf /usr/bin/python3 /usr/bin/python
            python --version  # Check Python version after update

      - run:
          name: Install pynacl dependencies
          command: |
            apk add --no-cache libffi-dev

      - run:
          name: Install pynacl
          command: |
            python3 -m pip install pynacl==1.4.0

      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py

      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest
